#!/bin/sh
#


if [ $# = 0 ];then
    echo "usage: all_to_utf8 filename, argument number should be only one."

elif [ $# -gt 1 ]; then
    echo " argument number should be only one."
    exit 0
elif [ $1 = recover ]; then
    for i in `ls *.all_to_utf8_tmp`; do
        mv $i ${i%.all_to_utf8_tmp}
    done
    exit 0
fi




filename=$1
if [ -f "$filename" ]; then
    # code=`file -I $filename|awk -F';' '{print $2}'`
    code=`enca -L zh_CN $filename|awk -F';' '{print $3}'`
    mv $filename $filename.all_to_utf8_tmp
    iconv -f $code -t utf-8 $filename.all_to_utf8_tmp > $filename
else
    echo file not exist.
fi

