#!/bin/sh
#


if [ $# = 0 ];then
    echo "usage: all_to_utf8 filename, argument number should be only one."

elif [ $# -gt 1 ]; then
    echo " argument number should be only one."
    exit 0
fi



filename=$1
code=`file -I $filename|awk -F'=' '{print $2}'`
mv $filename $filename.tmp
iconv -f $code -t utf-8 $filename.tmp > $filename
